<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property integer $id
 * @property string $title
 * @property string $date
 *
 * @property Gratter[] $gratters
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['title', 'required'],
            [['title'], 'string', 'max' => 255],
            [['title'], 'string', 'min' => 5],
            [['date'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ИД',
            'title' => 'Имя',
            'date' => 'Дата праздника'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGratters()
    {
        return $this->hasMany(Gratter::className(), ['category_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return CategoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new CategoryQuery(get_called_class());
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        if(strlen($this->date) === 0){
            $this->date = NULL;
        }
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}
